export const questions = {
    name: "Nombre y Apellido",
    birthDate: "Fecha de Nacimiento",
    sexualOrientation: "¿Cómo te identificas?",
    age: "Edad",
    country: "Pais de residencia",
    city: "Ciudad de residencia",
    originCountry: "Pais de Origen",
    email: "Correo electronico principal",
    secondaryEmail: "Correo secundario",
    phone: "Numero de telefono",
    whatsapp:"Whatsapp",
    facebook:"¿Tienes Facebook?",
    localGroups: "¿Formas parte de algún grupo o movimiento a nivel local, en tu país?",
    localGroupsName: "Si respondiste SÍ a la pregunta anterior, nombra los grupos y/o movimientos con los que trabajas localmente",
    outsideGroups: "¿Formas parte de algún grupo o red fuera de tu país?",
    outsideGroupsName: "Si respondiste SÍ a la pregunta anterior, nombra los grupos y/o movimientos con los que trabajas fuera de tu país",
    workInForum: "¿Te gustaría colaborar con el Foro Regional de GayLatino?",
    workingHours: "¿Cuántas horas a la semana crees poder dedicar al trabajo de GayLatino?",
    skills: "¿Qué habilidades y aptitudes crees poder aportar a nuestra red?",
    additionalInformation: "¿Hay algo que quieras agregar a tu aplicación?"
}